# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/pins.xdc

# Block Designs: bd/Bidirectional_Transmitter/Bidirectional_Transmitter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter || ORIG_REF_NAME==Bidirectional_Transmitter} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_processing_system7_0_0/Bidirectional_Transmitter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_processing_system7_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_processing_system7_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_axi_gpio_0_0/Bidirectional_Transmitter_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_axi_gpio_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_ps7_0_axi_periph_0/Bidirectional_Transmitter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_ps7_0_axi_periph_0 || ORIG_REF_NAME==Bidirectional_Transmitter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_rst_ps7_0_50M_0/Bidirectional_Transmitter_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_rst_ps7_0_50M_0 || ORIG_REF_NAME==Bidirectional_Transmitter_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_UART_Transmitter_0_0/Bidirectional_Transmitter_UART_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_UART_Transmitter_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_UART_Transmitter_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_UART_Reciever_0_0/Bidirectional_Transmitter_UART_Reciever_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_UART_Reciever_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_UART_Reciever_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_gpio_parse_0_0/Bidirectional_Transmitter_gpio_parse_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_gpio_parse_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_gpio_parse_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_xadc_wiz_0_0/Bidirectional_Transmitter_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_xadc_wiz_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_xbar_0/Bidirectional_Transmitter_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_xbar_0 || ORIG_REF_NAME==Bidirectional_Transmitter_xbar_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_xlconcat_0_0/Bidirectional_Transmitter_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_xlconcat_0_0 || ORIG_REF_NAME==Bidirectional_Transmitter_xlconcat_0_0} -quiet] -quiet

# IP: bd/Bidirectional_Transmitter/ip/Bidirectional_Transmitter_auto_pc_0/Bidirectional_Transmitter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Bidirectional_Transmitter_auto_pc_0 || ORIG_REF_NAME==Bidirectional_Transmitter_auto_pc_0} -quiet] -quiet

# XDC: bd/Bidirectional_Transmitter/Bidirectional_Transmitter_ooc.xdc
